name: weather_notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  geolocator: ^13.0.2
  http: ^1.3.0
  cloud_firestore: ^5.6.3
  intl: ^0.20.2
  google_places_autocomplete_text_field: ^1.1.0
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/